{{- if .Values.transmission.enabled -}}
---
### CONFIGMAP
## INIT-CONTAINER
apiVersion: v1
data:
  init-transmission.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    chown -R {{ .Values.general.puid }}:{{ .Values.general.pgid }} /transmission-config
    if [ ! -f /transmission-config/settings.json ]; then
        cp -n /init-transmission/settings.json /transmission-config/settings.json
        echo "### No configuration found, initialized with default settings ###"
    fi

  settings.json: |
    {
      "alt-speed-down": 50,
      "alt-speed-enabled": false,
      "alt-speed-time-begin": 540,
      "alt-speed-time-day": 127,
      "alt-speed-time-enabled": false,
      "alt-speed-time-end": 1020,
      "alt-speed-up": 50,
      "bind-address-ipv4": "127.0.0.1",
      "bind-address-ipv6": "::",
      "blocklist-enabled": false,
      "cache-size-mb": 4,
      "dht-enabled": true,
      "download-dir": "/{{ .Values.general.storage.subPaths.downloads }}/{{ .Values.general.storage.subPaths.transmission }}/complete",
      "download-queue-enabled": true,
      "download-queue-size": 5,
      "encryption": 1,
      "idle-seeding-limit": 30,
      "idle-seeding-limit-enabled": false,
      "incomplete-dir": "/{{ .Values.general.storage.subPaths.downloads }}/{{ .Values.general.storage.subPaths.transmission }}/incomplete",
      "incomplete-dir-enabled": true,
      "lpd-enabled": false,
      "message-level": 2,
      "peer-limit-global": 200,
      "peer-limit-per-torrent": 50,
      "peer-port": {{ .Values.transmission.service.peer.port }},
      "peer-port-random-on-start": false,
      "pex-enabled": true,
      "port-forwarding-enabled": true,
      "preallocation": 1,
      "rpc-authentication-required": {{ .Values.transmission.config.auth.enabled }},
      "rpc-bind-address": "127.0.0.1",
      "rpc-enabled": true,
      "rpc-password": {{ .Values.transmission.config.auth.password | quote }},
      "rpc-port": 9091,
      "rpc-username": {{ .Values.transmission.config.auth.username | quote }},
      "rpc-whitelist": "127.0.0.1",
      "rpc-whitelist-enabled": false,
      "start-added-torrents": true,
      "umask": 2,
      "watch-dir": "/watch",
      "watch-dir-enabled": true
    }
kind: ConfigMap
metadata:
  name: init-transmission-cm
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: transmission
    spec:
      securityContext:
        fsGroup: {{ .Values.general.pgid }}
      initContainers:
        - name: config-transmission
          image: docker.io/ubuntu:groovy
          command: ["/init-transmission/init-transmission.sh"]
          volumeMounts:
            - mountPath: /init-transmission
              name: init-files-transmission
            {{- if .Values.transmission.volume }}
            - name: {{ .Values.transmission.volume.name }}
              mountPath: /transmission-config
            {{- else }}
            - name: mediaserver-volume
              mountPath: "/transmission-config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
            {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
        - name: fix-downloads-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /downloads/{{ .Values.general.storage.subPaths.transmission }}/complete /downloads/{{ .Values.general.storage.subPaths.transmission }}/incomplete && chown -R {{ .Values.general.puid }}:{{ .Values.general.pgid }} /downloads"]
          volumeMounts:
            - name: mediaserver-volume
              mountPath: /downloads
          securityContext:
            runAsUser: 0
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:v3
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-creds
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-creds
                  key: password
            - name: VPN_PORT_FORWARDING
              value: "on"
          ports:
            - containerPort: 9091
              name: rpc
            - containerPort: {{ .Values.transmission.service.peer.port }}
              name: peer-tcp
              protocol: TCP
            - containerPort: {{ .Values.transmission.service.peer.port }}
              name: peer-udp
              protocol: UDP
          volumeMounts:
            - mountPath: /gluetun
              name: gluetun-volume
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: transmission-config
          image: "{{ .Values.transmission.container.image }}:{{ .Values.transmission.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          volumeMounts:
            {{- if .Values.transmission.volume }}
            - name: {{ .Values.transmission.volume.name }}
              mountPath: /config
            {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/transmission"
            {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.general.storage.subPaths.downloads }}"
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
          {{- with .Values.transmission.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.transmission.volume }}
        - name: {{ .Values.transmission.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.transmission.volume.name }}
        {{- end }}
        - name: init-files-transmission
          configMap:
            defaultMode: 493
            name: init-transmission-cm
        - name: gluetun-volume
          emptyDir: {}
      {{- with merge .Values.transmission.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.transmission.service.utp.type }}
  ports:
    - name: rpc
      port: 9091
      targetPort: 9091
    - name: peer-tcp
      port: {{ .Values.transmission.service.peer.port }}
      targetPort: {{ .Values.transmission.service.peer.port }}
      protocol: TCP
    - name: peer-udp
      port: {{ .Values.transmission.service.peer.port }}
      targetPort: {{ .Values.transmission.service.peer.port }}
      protocol: UDP
  selector:
    app: transmission
---
### INGRESS
{{ if .Values.transmission.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "media-transmission-auth@kubernetescrd"
    {{- with .Values.transmission.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.transmission.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.transmission.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.transmission.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: transmission-auth
  namespace: media
spec:
  basicAuth:
    secret: transmission-basic-auth
{{ end }}
{{ end }}
